### ISSUE TITLE
Regression: $slice limit must be positive

### ISSUE THREAD

**Issue by strugee** [e14n/databank-mongodb#12]
In pump.io we have a bug where many (most?) API calls cause "$slice limit must be positive" errors with this Databank driver. You can easily reproduce this by opening the web UI from an instance running this driver and just waiting for the autorefresh. You'll see the error in the console.

I did a bisection and 489016da1410c3c93ed6ed7f486193d9a78e91bb is the commit that regressed this. I've been meaning to confirm this is a bug in the driver, and not merely exposing a preexisting bug in pump, but seeing as I haven't had time and this being a pump bug is unlikely, I'm filing this issue anyway.

See pump-io/pump.io#1287 for where we're tracking this downstream.

**Comment by evanp** [comment]
I think this is fixed in 1.0.1
